export const TempData = [
  {
    name: "Jan",
    "Monthly Sales": 4000,
    "Active Users": 6000,
  },
  {
    name: "Feb",
    "Monthly Sales": 4000,
    "Active Users": 4000,
  },
  {
    name: "Mar",
    "Monthly Sales": 4000,
    "Active Users": 5000,
  },
  {
    name: "Apr",
    "Monthly Sales": 8000,
    "Active Users": 2000,
  },
  {
    name: "May",
    "Monthly Sales": 2000,
    "Active Users": 5000,
  },
  {
    name: "Jun",
    "Monthly Sales": 6000,
    "Active Users": 6000,
  },
  {
    name: "Jul",
    "Monthly Sales": 9000,
    "Active Users": 4000,
  },
  {
    name: "Aug",
    "Monthly Sales": 3000,
    "Active Users": 5000,
  },
  {
    name: "Sep",
    "Monthly Sales": 5022,
    "Active Users": 3000,
  },
  {
    name: "Oct",
    "Monthly Sales": 6000,
    "Active Users": 3873,
  },
  {
    name: "Nov",
    "Monthly Sales": 1009,
    "Active Users": 4000,
  },
  {
    name: "Dev",
    "Monthly Sales": 4000,
    "Active Users": 6000,
  },
];

export const UsersRows = [
  {
    id: 1,
    username: "Ayman A.",
    avatar: "https://bit.ly/3GqErl2",
    email: "ayman@email.com",
    status: 35,
    transactions: "£120",
  },
  {
    id: 2,
    username: "Ayman A.",
    avatar: "https://bit.ly/3GqErl2",
    email: "ayman@email.com",
    status: 35,
    transactions: "£120",
  },
  {
    id: 3,
    username: "Ayman A.",
    avatar: "https://bit.ly/3GqErl2",
    email: "ayman@email.com",
    status: 35,
    transactions: "£120",
  },
  {
    id: 4,
    username: "Ayman A.",
    avatar: "https://bit.ly/3GqErl2",
    email: "ayman@email.com",
    status: 35,
    transactions: "£120",
  },
  {
    id: 5,
    username: "Ayman A.",
    avatar: "https://bit.ly/3GqErl2",
    email: "ayman@email.com",
    status: 35,
    transactions: "£120",
  },
  {
    id: 6,
    username: "Ayman A.",
    avatar: "https://bit.ly/3GqErl2",
    email: "ayman@email.com",
    status: 35,
    transactions: "£120",
  },
  {
    id: 7,
    username: "Ayman A.",
    avatar: "https://bit.ly/3GqErl2",
    email: "ayman@email.com",
    status: 35,
    transactions: "£120",
  },
  {
    id: 8,
    username: "Ayman A.",
    avatar: "https://bit.ly/3GqErl2",
    email: "ayman@email.com",
    status: 35,
    transactions: "£120",
  },
  {
    id: 9,
    username: "Ayman A.",
    avatar: "https://bit.ly/3GqErl2",
    email: "ayman@email.com",
    status: 35,
    transactions: "£120",
  },
  {
    id: 10,
    username: "Ayman A.",
    avatar: "https://bit.ly/3GqErl2",
    email: "ayman@email.com",
    status: 35,
    transactions: "£120",
  },
];
